import { Stack, Typography, Button } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ML-GPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack
        width="100vw"
        minHeight="100vh"
        display="flex"
        justifyContent="center"
        alignItems="center"
      >
        <Typography variant="h5" fontWeight="700" marginBottom={10}>
          Try ML-GPT 👇
        </Typography>

        <textarea
          name="text"
          cols={70}
          rows={10}
          placeholder="Maximum of 250 characters"
          style={{ padding: "20px" }}
        />

        <button>Get results</button>
      </Stack>
    </>
  );
}
